item {
  id: 1
  name: 'Beagle Dog'
}

item {
	id: 2
	name : 'Bulldog'
}

item {
	id: 3
	name: 'German Shepherd Dog'
}

item {
	id: 4
	name: 'Golden Retriever Dog'
}

item {
	id: 5
	name: 'Labrador Dog'
}

item {
	id: 6
	name: 'Poodle Dog'
}

item {
	id: 7
	name: 'Rottweiler Dog'
}

item {
	id: 8
	name: 'Yorkshire Dog'
}